# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

host: 0.0.0.0

# Site settings
title: Micronode
email: info@micronode.com
description: > # this means to ignore newlines until "baseurl:"
  Modern software applications and services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: micronode
github_username: micronode 

# Build settings
markdown: kramdown
