site_name: Micronode
site_url: https://www.micronode.org
theme:
  name: material
  favicon: images/cherry.png
  logo: images/mnode_logo.png
repo_url: https://github.com/micronode/micronode.github.io
repo_name: micronode/micronode.github.io
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/micronode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Overview:
    - Introduction: index.md
  - Projects:
    - Overview: projectes/index.md
  - References:
    - Resources: resources.md
  - FAQ: faq.md
